name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: CocoaPod Install
      run: pod install
      
    - name: Clean and Build AppBidding-GoogleAdManager
      run: xcodebuild clean build -scheme AppBidding-GoogleAdManager -workspace CriteoSamples.xcworkspace -destination "platform=iOS Simulator,name=iPhone 11"

    - name: Clean and Build Standalone
      run: xcodebuild clean build -scheme Standalone -workspace CriteoSamples.xcworkspace -destination "platform=iOS Simulator,name=iPhone 11"
